### ISSUE TITLE
Change file extension to jsonld

### ISSUE THREAD

**Issue by AlasdairGray** [ammar257ammar/SWAT4HCLS2022-ChEMBL-bioschemas-mapping#2]
Some triplestores (e.g. GraphDB) cannot load `.json` files, they need the file extension to be `.jsonld`.

I suggest that the generated files are given the `.jsonld` extension.

**Comment by ammar257ammar** [comment]
Thanks for the tip!

I changed the extension of the saved file to "jsonld" in the notebook.
